baseURL = "https://bparvitte.github.io/quickstart/"
languageCode = "fr-fr"
title = "Bertrand Parvitte"
theme = "book"
relativeURLs = false
canonifyURLs = true

[params]
# BookTheme = 'dark'
BookPortableLinks = false


[markup.goldmark.renderer]
  unsafe = true

  [Params.source]
#    url = "https://bparvitte.github.io/quickstart/" # Mandatory, used in hugo-bare-min-theme single.html, baseof.html
